### PR TITLE
Added fastdtw

### PR DESCRIPTION
**Pull request by capkuro**
Hi, I'm implementing a speech comparison back-end and i used your library. In my journey of developing my application, I found out that the speed for calculating the DTW between a large number of MFCC coefficients is slow (in the context of my application). For that reason, fastdtw was implemented, by making use of scipy's  [cdist](https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.distance.cdist.html#Parameters) function which has optimised functions for calculating the distance between matrices.

This function supports giving the distance function as a parameter, or giving it as a string. If the latter is used, then cdist will be using an corresponding optimised function. Here below is a little code for time benchmarking purposes: 
```python
import numpy as np
from scipy.spatial.distance import cosine
from dtw import dtw, fastdtw
import timeit

x = np.random.rand(1000).reshape(-1,1)
y = np.random.rand(1000).reshape(-1,1)

start = timeit.default_timer()
fastdtw(x,y,cosine)
end = timeit.default_timer()
print ("DTW with scipy cosine distance:" ,end-start)
print "========"
start = timeit.default_timer()
fastdtw(x,y,'cosine')
end = timeit.default_timer()
print ("DTW with scipy cdist using cosine distance:",end-start)
```

And the output of this code in a I5-5gen with 8gb of ram is: 

```
('DTW with scipy cosine distance:', 47.640693556034876)
========
('DTW with scipy cdist using cosine distance:', 1.4689458024448427)
```
Also, thanks for sharing your code.
Sebastian

### CODE REVIEW

**Comment by pierre-rouanet** [comment]
Great add to the library! Thanks a lot!

**Comment by ludovicamicaroni3** [comment]
Hi, If I install the package dtw it cannot find this function on the import. shall I install something else?

**Comment by michael-haus** [comment]
If you check accelerated_dtw.py you will see the function got renamed from fastdtw to accelerated_dtw

**Comment by pierre-rouanet** [comment]
It has been renamed accelerated_dtw (see https://github.com/pierre-rouanet/dtw/pull/28)

**Comment by pankeda123** [comment]
Hi, this is really a very easy to use package, thank you for providing. I am using it for clustering large amounts of data，so I use the ‘accelerated_dtw’ function for calculation. But function ‘accelerated_dtw’ seems to be unable to adjust the parameter ‘w’, is there a way to solve this problem?

**Comment by maithakh** [comment]
Thanks  lot really this is much more faster than the dtw. If you have any paper let me know so that I reference it in my MSc. dissertation.
best regards,

**Pull request merged**
